import { Customer } from "../entities/customer";

const customersData: Customer[] = [
  {
    id: "1",
    createdAt: new Date(),
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    address: "123 Main St, Anytown, USA",
    password: "password123",
  },
  {
    id: "2",
    createdAt: new Date(),
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "234-567-8901",
    address: "456 Elm St, Othertown, USA",
    password: "password123",
  },
  {
    id: "3",
    createdAt: new Date(),
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phone: "345-678-9012",
    address: "789 Oak St, Sometown, USA",
    password: "password123",
  },
  {
    id: "4",
    createdAt: new Date(),
    firstName: "Bob",
    lastName: "Brown",
    email: "bob.brown@example.com",
    phone: "456-789-0123",
    address: "101 Pine St, Anothertown, USA",
    password: "password123",
  },
  {
    id: "5",
    createdAt: new Date(),
    firstName: "Charlie",
    lastName: "Davis",
    email: "charlie.davis@example.com",
    phone: "567-890-1234",
    address: "202 Birch St, Yetanothertown, USA",
    password: "password123",
  },
  {
    id: "6",
    createdAt: new Date(),
    firstName: "Emily",
    lastName: "Clark",
    email: "emily.clark@example.com",
    phone: "678-901-2345",
    address: "303 Cedar St, Anytown, USA",
    password: "password123",
  },
  {
    id: "7",
    createdAt: new Date(),
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    phone: "789-012-3456",
    address: "404 Spruce St, Othertown, USA",
    password: "password123",
  },
  {
    id: "8",
    createdAt: new Date(),
    firstName: "Olivia",
    lastName: "Garcia",
    email: "olivia.garcia@example.com",
    phone: "890-123-4567",
    address: "505 Willow St, Sometown, USA",
    password: "password123",
  },
  {
    id: "9",
    createdAt: new Date(),
    firstName: "Sophia",
    lastName: "Wilson",
    email: "sophia.wilson@example.com",
    phone: "901-234-5678",
    address: "606 Aspen St, Anothertown, USA",
    password: "password123",
  },
  {
    id: "10",
    createdAt: new Date(),
    firstName: "James",
    lastName: "Miller",
    email: "james.miller@example.com",
    phone: "012-345-6789",
    address: "707 Maple St, Yetanothertown, USA",
    password: "password123",
  },
];

export default customersData;
